export const STATES_CITIES = {
  'Andhra Pradesh': ['Visakhapatnam','Vijayawada','Guntur','Nellore','Kurnool','Tirupati','Rajahmundry'],
  'Assam': ['Guwahati','Dibrugarh','Silchar','Jorhat','Tezpur'],
  'Bihar': ['Patna','Gaya','Muzaffarpur','Bhagalpur','Darbhanga','Purnia'],
  'Chhattisgarh': ['Raipur','Bhilai','Bilaspur','Durg','Korba'],
  'Delhi': ['New Delhi','Central Delhi','North Delhi','South Delhi','East Delhi','West Delhi','Dwarka','Rohini'],
  'Goa': ['Panaji','Margao','Vasco da Gama','Mapusa'],
  'Gujarat': ['Ahmedabad','Surat','Vadodara','Rajkot','Bhavnagar','Jamnagar','Gandhinagar'],
  'Haryana': ['Gurugram','Faridabad','Panipat','Ambala','Karnal','Hisar','Rohtak','Sonipat'],
  'Himachal Pradesh': ['Shimla','Manali','Dharamshala','Solan','Mandi'],
  'Jharkhand': ['Ranchi','Jamshedpur','Dhanbad','Bokaro','Deoghar'],
  'Karnataka': ['Bengaluru','Mysuru','Mangaluru','Hubballi','Belagavi','Kalaburagi','Davangere'],
  'Kerala': ['Thiruvananthapuram','Kochi','Kozhikode','Thrissur','Kollam','Kannur','Alappuzha'],
  'Madhya Pradesh': ['Bhopal','Indore','Gwalior','Jabalpur','Ujjain','Sagar','Rewa'],
  'Maharashtra': ['Mumbai','Pune','Nagpur','Nashik','Thane','Aurangabad','Solapur','Amravati'],
  'Manipur': ['Imphal','Thoubal','Bishnupur'],
  'Meghalaya': ['Shillong','Tura'],
  'Odisha': ['Bhubaneswar','Cuttack','Rourkela','Berhampur','Sambalpur'],
  'Punjab': ['Ludhiana','Amritsar','Jalandhar','Patiala','Bathinda','Mohali','Pathankot'],
  'Rajasthan': ['Jaipur','Jodhpur','Kota','Bikaner','Ajmer','Udaipur','Alwar'],
  'Tamil Nadu': ['Chennai','Coimbatore','Madurai','Tiruchirappalli','Salem','Tirunelveli','Vellore'],
  'Telangana': ['Hyderabad','Warangal','Nizamabad','Karimnagar','Khammam'],
  'Uttar Pradesh': ['Lucknow','Kanpur','Agra','Varanasi','Ghaziabad','Noida','Meerut','Allahabad','Bareilly','Aligarh','Moradabad','Dadri','Mathura','Firozabad','Saharanpur','Gorakhpur','Faizabad','Jhansi','Muzaffarnagar','Rampur'],
  'Uttarakhand': ['Dehradun','Haridwar','Roorkee','Rishikesh','Haldwani'],
  'West Bengal': ['Kolkata','Howrah','Durgapur','Asansol','Siliguri','Bardhaman'],
  'Jammu and Kashmir': ['Srinagar','Jammu','Anantnag','Sopore'],
  'Chandigarh': ['Chandigarh'],
  'Puducherry': ['Puducherry'],
};

export const STATES = Object.keys(STATES_CITIES).sort();
